/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */

#if defined(QT_SHARED) || !defined(QT_STATIC)
#  if defined(QT_BUILD_CUSTOM_EXPORT_NAME_LIB)
#    define QPB_CUSTOM_EXPORT_NAME_EXPORT Q_DECL_EXPORT
#  else
#    define QPB_CUSTOM_EXPORT_NAME_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define QPB_CUSTOM_EXPORT_NAME_EXPORT
#endif

