version: 2
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

downstream_check:
  mode: build
  modules:
    ../qtdeclarative:
      ref: dev
  configurations:
    - rhel-8.4

machine_type:
  Build:
    cores: 8
  Test:
    cores: 4

instructions:
  Build:
    - !include "{{qt/qtbase}}/coin_qtbase_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
    - !include "{{qt/qtbase}}/coin_qtbase_test_docs.yaml"
