-
    Template: 'qtci-windows-10-x86_64-16'
    Compiler: 'MSVC2015'
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -developer-build -release -angle -qtnamespace TestNamespace -qtlibinfix TestInfix -nomake tests -openssl -I %OPENSSL_INCLUDE_x64% -L %OPENSSL_LIB_x64% -plugin-sql-mysql -plugin-sql-sqlite -plugin-sql-odbc -I %MYSQL_INCLUDE_x64% -L %MYSQL_LIB_x64% -plugin-sql-psql -I %POSTGRESQL_INCLUDE_x64% -L %POSTGRESQL_LIB_x64%'
-
    Template: 'qtci-windows-7-x86-3'
    Compiler: 'Mingw73'
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -developer-build -release -nomake tests -opengl dynamic -nomake examples -openssl -I %OPENSSL_INCLUDE_x86% -L %OPENSSL_LIB_x86% -plugin-sql-mysql -plugin-sql-sqlite -plugin-sql-odbc -I %MYSQL_INCLUDE_x86% -L %MYSQL_LIB_x86% -plugin-sql-psql -I %POSTGRESQL_INCLUDE_x86% -L %POSTGRESQL_LIB_x86% -platform win32-g++'
-
    Template: 'qtci-windows-10-x86_64-16'
    Target arch: 'x86'
    Compiler: 'MSVC2017'
    Features: ['Packaging']
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -debug-and-release -release -force-debug-info -nomake tests -opengl dynamic -nomake examples -openssl -I %OPENSSL_INCLUDE_x86% -L %OPENSSL_LIB_x86% -no-sql-mysql -plugin-sql-sqlite -plugin-sql-odbc -I %MYSQL_INCLUDE_x86% -L %MYSQL_LIB_x86% -plugin-sql-psql -I %POSTGRESQL_INCLUDE_x86% -L %POSTGRESQL_LIB_x86%'
-
    Template: 'qtci-windows-10-x86_64-16'
    Compiler: 'MSVC2015'
    Features: ['Packaging']
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -debug-and-release -release -force-debug-info -nomake tests -nomake examples -opengl dynamic -openssl -I %OPENSSL_INCLUDE_x64% -L %OPENSSL_LIB_x64% -no-sql-mysql -plugin-sql-sqlite -plugin-sql-odbc -I %MYSQL_INCLUDE_x64% -L %MYSQL_LIB_x64% -plugin-sql-psql -I %POSTGRESQL_INCLUDE_x64% -L %POSTGRESQL_LIB_x64%'
-
    Template: 'qtci-windows-10-x86_64-16'
    Target os: 'WinRT_10'
    Target arch: 'x86'
    Compiler: 'MSVC2015'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -debug-and-release -release -force-debug-info -nomake tests -nomake examples -no-sql-mysql -platform win32-msvc2015 -xplatform winrt-x86-msvc2015'
-
    Template: 'qtci-windows-10-x86_64-16'
    Target os: 'WinRT_10'
    Target arch: 'armv7'
    Compiler: 'MSVC2015'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -debug-and-release -release -force-debug-info -nomake tests -nomake examples -no-sql-mysql -platform win32-msvc2015 -xplatform winrt-arm-msvc2015'
-
    Template: 'qtci-windows-10-x86_64-16'
    Compiler: 'MSVC2017'
    Features: ['Packaging']
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -debug-and-release -release -force-debug-info -nomake tests -opengl dynamic -nomake examples -openssl -I %OPENSSL_INCLUDE_x64% -L %OPENSSL_LIB_x64% -no-sql-mysql -plugin-sql-sqlite -plugin-sql-odbc -I %MYSQL_INCLUDE_x64% -L %MYSQL_LIB_x64% -plugin-sql-psql -I %POSTGRESQL_INCLUDE_x64% -L %POSTGRESQL_LIB_x64%'
-
    Template: 'qtci-windows-10-x86_64-16'
    Target os: 'Android_ANY'
    Target arch: 'x86'
    Compiler: 'Mingw73'
    Target compiler: 'Clang'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix c:\Users\qt\work\install -release -nomake tests -nomake examples -no-sql-mysql -no-dbus -opengl es2 -sysconfdir /etc/xdg -openssl -I c:\utils\openssl-android-master\include -xplatform android-clang -android-sdk C:\Utils\Android -android-ndk c:\Utils\Android\android-ndk-r19c -android-arch x86'
-
    Template: 'qtci-linux-Ubuntu-16.04-x86_64-2'
    Compiler: 'GCC'
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -nomake tests -R . -qtlibinfix TestInfix -qtnamespace TestNamespace -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -force-debug-info -nomake tests -no-widgets -nomake examples -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Features: ['OutOfSourceBuild', 'Documentation']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -nomake tests -R . -qtlibinfix TestInfix -qtnamespace TestNamespace -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -nomake tests -no-gui -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -nomake tests -no-opengl -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'

-
    Template: 'qtci-linux-openSUSE-42.3-x86_64'
    Compiler: 'GCC'
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -nomake tests -nomake examples -no-pch -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-openSUSE-42.3-x86_64'
    Compiler: 'ICC_18'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -nomake tests -nomake examples -no-pch -system-sqlite -R . -platform linux-icc-64 -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-openSUSE-42.3-x86_64'
    Target os: 'WebAssembly'
    Compiler: 'GCC'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -release -static -nomake tests -nomake examples -no-sql-mysql -no-pch -no-dbus -no-headersclean -no-ssl -no-warnings-are-errors -no-feature-thread -xplatform wasm-emscripten'
-
    Template: 'qtci-linux-SLES-12-x86_64'
    Compiler: 'GCC'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -no-sql-mysql -no-pch -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-SLES-15-x86_64'
    Compiler: 'GCC'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -developer-build -no-sql-mysql -no-pch -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib'
-
    Template: 'qtci-linux-RHEL-7.4-x86_64'
    Compiler: 'GCC'
    Features: ['Packaging']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -release -nomake tests -nomake examples -no-libudev -no-use-gold-linker -force-debug-info -separate-debug-info -no-sql-mysql -plugin-sql-psql -plugin-sql-sqlite -qt-libjpeg -qt-libpng -qt-xcb -sysconfdir /etc/xdg -qt-pcre -qt-harfbuzz -R . -openssl -I {{.Env.OPENSSL_HOME}}/include -L {{.Env.OPENSSL_HOME}}/lib QMAKE_LFLAGS_APP+=-s'
-
    Template: 'qtci-macos-10.13-x86_64-3'
    Compiler: 'Clang'
    Features: ['Packaging']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -debug-and-release -release -separate-debug-info -nomake tests -nomake examples -no-sql-mysql -plugin-sql-psql -plugin-sql-sqlite -sysconfdir /Library/Preferences/Qt -I/usr/local/opt/openssl/include'
-
    Template: 'qtci-macos-10.14-x86_64'
    Compiler: 'Clang'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -debug-and-release -release -separate-debug-info -nomake tests -no-sql-mysql -plugin-sql-psql -plugin-sql-sqlite -sysconfdir /Library/Preferences/Qt -I/usr/local/opt/openssl/include'
-
    Template: 'qtci-macos-10.12-x86_64-9'
    Compiler: 'Clang'
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -developer-build -release -no-pch -no-framework -qtnamespace TestNamespace -nomake tests -nomake examples -I/usr/local/opt/openssl/include'
-
    Template: 'qtci-macos-10.13-x86_64-3'
    Target os: 'IOS_ANY'
    Target arch: 'multi'
    Compiler: 'Clang'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -debug-and-release -nomake tests -no-icu -nomake examples -no-sql-mysql -no-sql-psql -plugin-sql-sqlite -static -xplatform macx-ios-clang'
-
    Template: 'qtci-macos-10.13-x86_64-3'
    Target os: 'TvOS_ANY'
    Target arch: 'multi'
    Compiler: 'Clang'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -debug-and-release -nomake tests -nomake examples -no-sql-mysql -no-sql-psql -plugin-sql-sqlite -xplatform macx-tvos-clang'
-
    Template: 'qtci-macos-10.13-x86_64-3'
    Target os: 'WatchOS_ANY'
    Target arch: 'multi'
    Compiler: 'Clang'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -debug-and-release -nomake tests -nomake examples -no-sql-mysql -no-sql-psql -plugin-sql-sqlite -xplatform macx-watchos-clang'
-
    Template: 'qtci-macos-10.13-x86_64-3'
    Target os: 'Android_ANY'
    Target arch: 'x86'
    Compiler: 'Clang'
    Target compiler: 'Clang'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /Users/qt/work/install -release -nomake tests -nomake examples -no-sql-mysql -no-dbus -no-qpa-platform-guard -opengl es2 -sysconfdir /etc/xdg -openssl -I /usr/local/opt/openssl/include -xplatform android-clang -android-sdk /opt/android/sdk -android-ndk /opt/android/android-ndk-r19c -android-ndk-host darwin-x86_64 -android-arch x86'
-
    Template: 'qtci-linux-RHEL-7.4-x86_64'
    Target os: 'Android_ANY'
    Target arch: 'x86'
    Compiler: 'GCC'
    Target compiler: 'Clang'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -release -nomake tests -nomake examples -no-sql-mysql -no-dbus -no-use-gold-linker -no-qpa-platform-guard -opengl es2 -sysconfdir /etc/xdg -openssl -I {{.Env.OPENSSL_ANDROID_HOME}}/include -xplatform android-clang -android-sdk /opt/android/sdk -android-ndk /opt/android/android-ndk-r19c -android-ndk-host linux-x86_64 -android-arch x86'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Target os: 'QEMU'
    Target arch: 'armv7'
    Compiler: 'GCC'
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -release -nomake tests -nomake examples -no-xcb -R . -openssl -device linux-imx7-g++ -device-option CROSS_COMPILE=/opt/yocto-armv7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi- -device-option DISTRO_OPTS="hard-float boot2qt" -sysroot /opt/yocto-armv7/sysroots/armv7ahf-neon-poky-linux-gnueabi -extprefix /home/qt/work/install -mysql_config /opt/yocto-armv7/sysroots/armv7ahf-neon-poky-linux-gnueabi/usr/bin/mysql_config -psql_config /dev/null -tslib'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Target os: 'QEMU'
    Target arch: 'arm64'
    Compiler: 'GCC'
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -release -nomake tests -nomake examples -no-xcb -R . -openssl -device linux-generic-g++ -device-option CROSS_COMPILE=/opt/yocto-arm64/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux- -device-option DISTRO_OPTS=boot2qt -sysroot /opt/yocto-arm64/sysroots/aarch64-poky-linux -extprefix /home/qt/work/install -mysql_config /opt/yocto-arm64/sysroots/aarch64-poky-linux/usr/bin/mysql_config -psql_config /dev/null -tslib'
-
    Template: 'qtci-linux-Ubuntu-18.04-x86_64'
    Compiler: 'GCC'
    Features: ['TestOnly', 'LicenseCheck']
-
    Template: 'qtci-linux-RHEL-7.4-x86_64'
    Target os: 'INTEGRITY_11_04'
    Target arch: 'armv7'
    Compiler: 'GCC'
    Features: ['DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -release -nomake tests -nomake examples -no-use-gold-linker -opengl es2 -xplatform integrity-armv7-imx6'
-
    Template: 'qtci-linux-RHEL-7.4-x86_64'
    Target os: 'QNX_700'
    Target arch: 'armv7'
    Compiler: 'GCC'
    Features: ['Packaging', 'DisableTests']
    Configure arguments: '-opensource -confirm-license -verbose -prefix /home/qt/work/install -release -nomake tests -nomake examples -no-use-gold-linker -opengl es2 -no-sql-mysql -qpa qnx -xplatform qnx-armle-v7-qcc'
