/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "5.12.12"

#define QTUITOOLS_VERSION 0x050C0C

#endif // QT_QTUITOOLS_VERSION_H
