# Call either qt-cmake or qt-configure-module depending on whether the
# UseConfigure platform configuration feature is set.
# We should remove the cmake branch, once all platform configurations
# are ported to use configure.
type: Group
instructions:
  - type: Group
    enable_if:
      condition: property
      property: features
      contains_value: UseConfigure
    instructions:
      - type: EnvironmentVariable
        variableName: CONFIGURE_EXECUTABLE
        variableValue: "{{.InstallDir}}{{.Env.INSTALL_DIR_SUFFIX}}{{.Env.CI_PATH_SEP}}bin{{.Env.CI_PATH_SEP}}qt-configure-module"
        disable_if:
          condition: property
          property: host.os
          equals_value: Windows
      - type: EnvironmentVariable
        variableName: CONFIGURE_EXECUTABLE
        variableValue: "{{.InstallDir}}{{.Env.INSTALL_DIR_SUFFIX}}{{.Env.CI_PATH_SEP}}bin{{.Env.CI_PATH_SEP}}qt-configure-module.bat"
        enable_if:
          condition: property
          property: host.os
          equals_value: Windows
  - type: Group
    disable_if:
      condition: property
      property: features
      contains_value: UseConfigure
    instructions:
      - type: EnvironmentVariable
        variableName: CONFIGURE_EXECUTABLE
        variableValue: "{{.InstallDir}}{{.Env.INSTALL_DIR_SUFFIX}}{{.Env.CI_PATH_SEP}}libexec{{.Env.CI_PATH_SEP}}qt-cmake-private"
        disable_if:
          condition: property
          property: host.os
          equals_value: Windows
      - type: EnvironmentVariable
        variableName: CONFIGURE_EXECUTABLE
        variableValue: "{{.InstallDir}}{{.Env.INSTALL_DIR_SUFFIX}}{{.Env.CI_PATH_SEP}}bin{{.Env.CI_PATH_SEP}}qt-cmake-private.bat"
        enable_if:
          condition: property
          property: host.os
          equals_value: Windows
