version: 2
accept_configuration:
  condition: and
  conditions:
    - condition: property
      property: features
      not_contains_value: Disable
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: property
              property: target.os
              not_equals_value: MacOS
            - condition: and
              conditions:
                - condition: property
                  property: target.os
                  equals_value: MacOS
                - condition: property
                  property: target.arch
                  not_equals_value: ARM64

instructions:
  Build:
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - type: Group
      instructions:
        - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
        - !include "{{qt/qtbase}}/coin_module_test_docs.yaml"
      enable_if:
        condition: property
        property: target.os
        not_equals_value: QNX
