SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtmockplugins2version.h QtMockPlugins2Version QtMockPlugins2 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
