SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtxkbcommonsupportversion.h QtXkbCommonSupportVersion QtXkbCommonSupport 
SYNCQT.PRIVATE_HEADER_FILES = qxkbcommon_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
